spring.application.name=spring-jooq-liquibase
spring.sql.init.mode=always

# Specifies the location of the master changelog file within the classpath
spring.liquibase.change-log=classpath:db/common-master-changelog.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/adani?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=Qwerty@1
