create schema if not exists tds;

create sequence if not exists api_key_id_seq;

create sequence if not exists audit_log_id_seq;

create sequence if not exists certificate_seq;

create sequence if not exists credentials_id_seq;

create sequence if not exists deductee_status_id_seq;

create sequence if not exists fifteen_ca_form_seq increment by 50;

create sequence if not exists hibernate_sequence;

create sequence if not exists pan_seq;

create sequence if not exists pan_verification_id_seq;

create sequence if not exists rate_id_seq;

create sequence if not exists transaction_audit_id_seq;

create sequence if not exists user_id_seq;

create sequence if not exists workspace_id_seq;

alter sequence if exists tds.email_settings_id_seq set schema public;

alter sequence if exists tds.general_settings_id_seq set schema public;

create sequence if not exists email_settings_id_seq;

create sequence if not exists general_settings_id_seq;

create table if not exists audit_log
(
    id              serial
        primary key,
    schema_name     text,
    table_name      text,
    record_id       bigint,
    operation_type  text,
    changed_at      timestamp default now(),
    changed_by      bigint,
    original_values jsonb,
    new_values      jsonb
);

create table if not exists deductee_category
(
    id    bigint not null
        constraint pk_deductee_category
            primary key,
    label varchar(255)
);

create table if not exists deductee_status
(
    id                  bigint generated by default as identity
        constraint pk_deducteestatus
            primary key,
    code                varchar(255),
    deductee_type       integer,
    description         varchar(500),
    remarks             varchar(500),
    surcharge_mandatory boolean,
    surcharge_threshold double precision
);

create table if not exists deductor_category
(
    id    bigint not null
        constraint pk_deductor_category
            primary key,
    label varchar(255),
    code  varchar(1)
);

create table if not exists email_settings
(
    id            bigint default nextval('public.email_settings_id_seq'::regclass) not null
        constraint pk_email_settings
            primary key,
    tls_enabled   boolean                                                       not null,
    host          varchar(255)                                                  not null,
    port          integer                                                       not null,
    username      varchar(255),
    password      varchar(255),
    from_email    varchar(255),
    default_email varchar(255)
);

create table if not exists license
(
    id             bigint not null
        primary key,
    activated_date date,
    product_key    varchar(255),
    status         varchar(255)
);

create table if not exists pan_details
(
    id                bigint default nextval('pan_seq'::regclass) not null
        constraint pk_pandetails
            primary key,
    pan               varchar(255)
        constraint uc_pandetails_pan
            unique,
    status            varchar(255),
    specified_person  boolean                                     not null,
    pan_aadhar_linked boolean                                     not null,
    pan_name          varchar(255)
);

create table if not exists pan_verification_history
(
    id             bigint default nextval('pan_verification_id_seq'::regclass) not null
        constraint pk_panverificationhistory
            primary key,
    request_id     varchar(255),
    requested_date date
);

create table if not exists rate
(
    id                       bigint  default nextval('rate_id_seq'::regclass) not null
        primary key,
    edu_cess                 numeric(19, 2),
    from_date                date,
    net_rate_with_sc         numeric(19, 2),
    net_rate_without_sc      numeric(19, 2),
    notes                    varchar(255),
    round_off                integer                                          not null,
    surcharge                numeric(19, 2),
    tds                      numeric(19, 2),
    tds_code                 varchar(255),
    tds_sub_code             varchar(255),
    ds_code varchar(255),
    deductee_status_fk       bigint
        constraint fk_rate_deducteestatus
            references deductee_status,
    version                  integer default 0                                not null,
    created_at               timestamp,
    created_by               bigint,
    modified_at              timestamp,
    modified_by              bigint,
    threshold_amt            numeric(19, 4),
    threshold_limit_override boolean default false,
    constraint uk_rate
        unique (tds_code, tds_sub_code, deductee_status_fk, from_date)
);

create table if not exists remitt_country
(
    code    varchar(255) not null
        constraint pk_remitt_country
            primary key,
    country varchar(255)
);

create table if not exists remitt_nature
(
    code   varchar(255) not null
        primary key,
    nature varchar(255)
);

create table if not exists tds_code
(
    tds_code      varchar(255) not null
        primary key,
    descr         varchar(255),
    e_form_no     varchar(255),
    lower_cert_yn boolean,
    self_decl     boolean,
    tds_section   varchar(255),
    threshold_amt numeric(19, 2),
    flags         jsonb
);

create table if not exists tds_sub_code
(
    tds_sub_code varchar(255)      not null
        primary key,
    created_at   timestamp,
    created_by   bigint,
    modified_at  timestamp,
    modified_by  bigint,
    version      integer default 0 not null,
    desc_16a     varchar(255),
    descr        varchar(255)
);

create table if not exists user_detail
(
    id                     bigint  default nextval('user_id_seq'::regclass) not null
        primary key,
    company                varchar(255),
    email                  varchar(255)                                     not null
        constraint uk_user_detail_email
            unique,
    failure_login_attempts integer,
    is_admin               boolean default false                            not null,
    last_logged_in_time    timestamp,
    locked                 boolean,
    name                   varchar(255)                                     not null,
    password               varchar(255)                                     not null,
    token_count            integer,
    temporary_password     boolean default false                            not null
);

create table if not exists workspace
(
    id             bigint default nextval('workspace_id_seq'::regclass) not null
        primary key,
    financial_year varchar(255),
    form_no        varchar(255),
    name           varchar(255),
    type           varchar(20)
        constraint check_types
            check ((type)::text = ANY
                   (ARRAY [('WK_TDSPAC'::character varying)::text, ('WK_34AB'::character varying)::text, ('WK_26AS'::character varying)::text])),
    properties     jsonb
);

create table if not exists api_key
(
    id           integer default nextval('api_key_id_seq'::regclass) not null
        constraint pk_api_key
            primary key,
    version      integer                                             not null,
    created_at   timestamp,
    created_by   bigint,
    modified_at  timestamp,
    modified_by  bigint,
    key          varchar(500)                                        not null,
    name         varchar(255),
    workspace_fk bigint
        constraint fk_api_key_on_workspace_fk
            references workspace
);

create table if not exists certificate
(
    id                 bigint default nextval('certificate_seq'::regclass) not null
        primary key,
    amount             numeric(19, 2),
    certificate_number varchar(255),
    certificate_type   varchar(255),
    from_date          date,
    pan                varchar(255),
    rate               numeric(19, 2),
    request_number     varchar(255),
    section            varchar(255),
    to_date            date,
    financial_year     varchar(255),
    workspace_fk       bigint
        constraint fk_certificate_workspace
            references workspace,
    utilized           numeric(19, 2),
    name               varchar(255),
    sub_section        varchar(255)
);

create table if not exists credentials
(
    id               bigint default nextval('credentials_id_seq'::regclass) not null
        constraint pk_credentials
            primary key,
    username         varchar(255),
    password         varchar(255),
    pan              varchar(255),
    tan              varchar(255),
    credentials_type varchar(255),
    workspace_fk     bigint
        constraint fk_credentials_on_workspace_fk
            references workspace
);

create table if not exists fifteen_ca_form
(
    id                    bigint not null
        primary key,
    ack_dt                varchar(255),
    ack_num               varchar(255),
    country_of_remittance varchar(255),
    entity_num            varchar(255),
    filing_type_cd        varchar(255),
    filling_mode          varchar(255),
    form_pan_id           bigint not null,
    form_part             varchar(255),
    form_status           varchar(255),
    form_type_cd          varchar(255),
    ref_month             bigint not null,
    ref_year              bigint not null,
    ref_year_type         varchar(255),
    remittee_name         varchar(255),
    submit_user_id        varchar(255),
    transaction_no        varchar(255),
    updated_tmstamp       varchar(255),
    ver_status            varchar(255),
    workspace_fk          bigint
        constraint fk_fifteen_ca_form_workspace
            references workspace
);

create table if not exists general_settings
(
    id           bigint default nextval('public.general_settings_id_seq'::regclass) not null
        constraint pk_general_settings
            primary key,
    key          varchar(255),
    value        varchar(255),
    workspace_fk bigint
        constraint fk_general_settings_workspace
            references workspace
);

create table if not exists transaction_audit
(
    id            bigint default nextval('transaction_audit_id_seq'::regclass) not null
        constraint pk_transaction_audit
            primary key,
    workspace_fk  bigint
        constraint fk_transactionaudit_on_workspace_fk
            references workspace,
    uploaded_date timestamp,
    status        boolean                                                      not null,
    upload_id     bigint,
    remarks       varchar(255),
    user_fk       bigint
        constraint fk_transaction_audit_user
            references user_detail
);

create table if not exists workspace_users
(
    user_fk      bigint                                                               not null
        constraint fk_woruse_on_user
            references user_detail,
    workspace_fk bigint                                                               not null
        constraint fk_woruse_on_workspace
            references workspace
            on delete cascade,
    is_active    boolean   default false,
    last_used_at timestamp default '1970-01-01 00:00:00'::timestamp without time zone not null,
    constraint pk_workspace_users
        primary key (user_fk, workspace_fk)
);
